# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'REIBeaconsApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for REIBeaconsApp
    pod 'Firebase'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'SVProgressHUD'
    pod 'Firebase/Core'
    pod 'ChameleonFramework'
    pod 'EstimoteSDK'
    pod 'EstimoteProximitySDK'
    pod 'RealmSwift'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
        config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        end
    end
end
